name = "StringMethod"
uuid = "e62e6a7e-3b2b-4391-b20a-030a7103b929"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]
version = "0.3.1"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
DataInterpolations = "6.5.2"
julia = "1.10"
